version: "2"

linters:
  enable:
    - bodyclose
    - errorlint
    - gosec
    - misspell
    - rowserrcheck
    - sqlclosecheck
  exclusions:
    presets:
      - std-error-handling

formatters:
  enable:
    - gofmt
